spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

eureka:
  client:
    enabled: false

server:
  port: 5678